# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.TextField(),
        ),
    ]
